# Generated by Django 3.1.7 on 2021-04-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='email',
            field=models.EmailField(default='example@mail.id', max_length=254),
        ),
    ]
