# Generated by Django 3.1.7 on 2021-04-17 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20210417_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='tanggallahir',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
