# Generated by Django 3.1.7 on 2021-04-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_guru_tanggallahir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='namaguru',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guru',
            name='nipguru',
            field=models.IntegerField(max_length=12),
        ),
    ]
