# Generated by Django 3.1.7 on 2021-04-18 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_auto_20210418_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='nipguru',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
