# Generated by Django 3.1.7 on 2021-04-18 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20210418_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='kelaminguru',
            field=models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], max_length=10),
        ),
        migrations.AlterField(
            model_name='guru',
            name='nipguru',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
        migrations.AlterField(
            model_name='guru',
            name='tanggallahir',
            field=models.DateField(),
        ),
    ]
