# Generated by Django 3.1.7 on 2021-04-18 23:57

from django.db import migrations, models
import panel.validator


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_auto_20210418_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profsek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='guru',
            name='email',
            field=models.EmailField(default='example@mail.id', max_length=254, validators=[panel.validator.val_email]),
        ),
    ]
