# Generated by Django 3.1.7 on 2021-04-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_auto_20210418_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='namakampus',
            field=models.CharField(default='stmmik sz nw anjani', max_length=50),
            preserve_default=False,
        ),
    ]
