# Generated by Django 3.1.7 on 2021-04-26 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_guru_namakampus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profsek',
            new_name='Profil',
        ),
    ]
